### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by MattRandall231** [blakeshelley10/CampUs#1]
User Story: As a site visitor, I want to be able to securely log in to CampUs, so that I can store my preferences for clubs and activities. 

Front End: Needs to provide a user sign-up page (to take in user data) and a log-in page (to authenticate user data). The sign-up page will ask the user questions about themselves and post that information to the server. The log-in page will take in a username and password and post that information to the server, being provided with a success or failure login result.

Back End: Needs to store user information in a sqlite database, using a hash function for the passwords. Must be able to compare hashed passwords and keep track of users currently logged in. Return success or failure back to frontend for login attempts.

**Comment by hadiplays** [comment]
Also for backend we need to have the register route identify if the user is signing up with an email which has already been used for a different account. The application should inform users to login if the email they tried registering with has already been used.

**Comment by hadiplays** [comment]
Adding another note to remember to change the way the register and login functions check the user, as its possible to just use the findUser function instead.
